---
env:
  es2020: true
  node: true
extends:
  - airbnb-base
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
rules: {}
