---
env:
  es2020: true
  node: true
extends:
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
parserOptions:
  project: ./tsconfig.json
rules:
  react/jsx-one-expression-per-line: 'off'
  import/prefer-default-export: 'off'
