---
env:
  es2020: true
  node: true
extends:
  - airbnb-typescript/base
  - plugin:jsx-a11y/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
parserOptions:
  project: ./tsconfig.json
rules:
  import/prefer-default-export: 'off'
