---
env:
  es2020: true
  node: true
extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
parserOptions:
  project: ./tsconfig.json
rules: {}
